submission_rules.adoc
DK and Guenther example system json's for submitters
=> Updating example json metadata

TERMS OF USE.md
=> Update TERMS OF USE.md

submission_rules.adoc
Clarifying the categories for various software components in a submission, and methods for reproduction. Should be non controversial.
Also, updates to match rules specified elsewhere in the document for Available category submissions.
=> clarifications for source requirements

submission_rules.adoc
=> Fix training rule issue 320

submission_rules.adoc
Fix #324  Clarify Logging Source of Truth for Logging
=> Fix #324 Clarify Logging Source of Truth for Logging

submission_rules.adoc
Fixes  Training issue 340 Section 5.11 in submission_rules is blank.
=> Fix #340 Section 5.11 in submission_rules is blank.

submission_rules.adoc
=> Fixes #356 Submission Events and Timeline

submission_rules.adoc
Fixes Training issue 370 Ensure that all submitters have a review
=> Fix 370 Ensure that all submitters have a review

submission_rules.adoc
renaming from /audit to /compliance to avoid confusion
=> renaming compliance log directory

submission_rules.adoc
@tjablin @DilipSequeira @guschmue
=> update server run count

submission_rules.adoc
they are for inference closed division only
@tjablin @DilipSequeira @petermattson
=> clarify compliance tests

submission_rules.adoc
Added link to script.
@guschmue @TheKanter @christ1ne
=> Updating Submission Privacy section

submission_rules.adoc
This command clarifies, where to get the mlperf_logging package from.
=> Verification update

submission_rules.adoc
Source code pertaining to atleast model definition or model implementation should always be provided in the submission repo for all categories (Available, preview, rdi etc) and all divisions (open, close).
=> Source code requirements for reproducibility for all categories

RESULTS_GUIDELINES.md
This is a merge-able duplicate of #69 to resolve the conflicts due to direct changes as mentioned in
https://github.com/mlcommons/policies/pull/69#issuecomment-848946375
Update includes:
Brief Introduction
Clarify comparisons of Unofficial self-measured vs Official scores
Process for handling violations, remedies & penalties
=> Update RESULTS_GUIDELINES.md (1)

submission_rules.adoc
Final results on Thursday, not friday to support distribution to press.
=> Update rules schedule

MLPerf_Results_Messaging_Guidelines.adoc
=> MLC is registered

submission_rules.adoc
Modify the schedule to reflect what we actually plan on doing and what presumably people will plan on doing in the future.
=> Revise stated schedule.

MLPerf_Results_Messaging_Guidelines.adoc
3 business days per legal discussion
=> adding timeline for violation takedown

submission_rules.adoc
=> Remove compliance_checker_log.txt requirement

submission_rules.adoc
Stems from https://github.com/mlcommons/policies/pull/180
=> Clarify review committee composition
